services:
  - type: web
    name: learntube-backend
    runtime: node
    buildCommand: npm install && npm run db:migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: learntube-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://learntube-yi19.onrender.com/api/v1/auth/google/callback
      - key: YOUTUBE_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://learntube-orcin.vercel.app

databases:
  - name: learntube-db
    databaseName: learntube
    user: learntube_user
